//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 银行储蓄管理
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int 员工编号 { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public string 密码 { get; set; }
        public decimal 工资 { get; set; }
        public string 身份 { get; set; }
    }
}
